apiVersion: v1
kind: Service
metadata:
  name: my-flaskapp-service
spec:
  type: LoadBalancer
  selector:
    app: my-flaskapp-deployment
  ports:
    - port: 4001
      targetPort: 8000
      protocol: TCP


